/// Generated by AssetsRefGenerator on 2020/11/06
class Res {
  // static const String Pacifico-Regular = "assets/fonts/Pacifico-Regular.ttf";
  // static const String Quicksand-Bold = "assets/fonts/Quicksand-Bold.ttf";
  // static const String Quicksand-Regular = "assets/fonts/Quicksand-Regular.ttf";
  static const String background = "assets/images/background.png";
  static const String facebook_logo = "assets/images/facebook_logo.jpg";
  static const String google_logo = "assets/images/google_logo.png";
}
